{
 "title": "Codex Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "experiment_id",
    "label": "Experiment ID",
    "query": {
     "query": "label_values(nim_gc_heap_instance_occupied_bytes,experiment_id)"
    }
   },
   {
    "name": "experiment_type",
    "label": "Type of experiment.",
    "query": {
     "query": "label_values(nim_gc_heap_instance_occupied_bytes,job)"
    }
   },
   {
    "name": "node",
    "label": "Node Index",
    "query": {
     "query": "label_values(nim_gc_heap_instance_occupied_bytes,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Blockexchange Blocks Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "codex_block_exchange_blocks_sent_total",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  {
   "title": "Block Exchange Blocks Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "codex_block_exchange_blocks_received_total",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Heap Usage per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (node) (nim_gc_heap_instance_occupied_bytes{experiment_id=~\"$experiment_id\"})",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  {
   "title": "Detailed Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{job=~\"${experiment_type}\",experiment_id=~\"${experiment_id}\",node=~\"${node}\"}",
     "legendFormat": "{{type_name}} - node {{node}}"
    }
   ]
  },
  {
   "title": "Total Object Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "nim_gc_heap_instance_count", "legendFormat": "Node {{node}}" }
   ]
  },
  {
   "title": "refc ZCT Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "nim_gc_zct_capacity", "legendFormat": "Node {{node}}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } }
 ]
}