name: Lint and Test the Logos Storage Local Harness

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get Logos Storage
      run: ./scripts/get-logos-storage.sh /usr/local/bin

    - name: Lint
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: >-
          test/bats
          test/test_helper

    - name: Run Tests
      run: ./test/bats/bin/bats test/
